<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ListeningQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
//        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('listening_questions')->truncate();
        DB::table('listening_questions')->insert([
            [
                'id' => 1,
                'listening_id' => 1,
                'title' => 'Next you will listen to four statements. Choose the one that best describes what you see in the picture.',
                'answer' => 'The woman is wearing glasses.;There is a note on the keyboard.;The woman is facing the monitor.;There is a lamp above the computer.',
                'correct_answer' => 'The woman is facing the monitor.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'listening_id' => 1,
                'title' => 'What is the purpose of the announcement?',
                'answer' => 'To criticize a feminist novel; To describe a guest of a television show; To introduce a newly launched television program; To raise sales of a novel',
                'correct_answer' => 'To criticize a feminist novel',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'listening_id' => 1,
                'title' => 'What is the announcement intended for?',
                'answer' => 'Giving information on government financial aid; Motivating employees to pursue an academic career; Strengthening the scholarship eligibility requirements; Supporting the children of employees',
                'correct_answer' => 'Giving information on government financial aid',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'listening_id' => 2,
                'title' => 'Next you will listen to four statements. Choose the one that best describes what you see in the picture.',
                'answer' => 'The people are wearing coats.;The boat is in the water.;The life-jackets are on the boat.;The drum is in front of the chair.',
                'correct_answer' => 'The drum is in front of the chair.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'listening_id' => 2,
                'title' => 'What is the main point of this letter?',
                'answer' => 'To discuss a membership upgrade; To suggest improvement of the facilities; To inform a health club of disapproval about a cancellation fee; To ask the gym to accept a refund request',
                'correct_answer' => 'To discuss a membership upgrade',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'listening_id' => 2,
                'title' => 'Why is Ms. Londale unhappy with her club membership?',
                'answer' => 'The gym didn\'t provide enough information initially.; The club facilities are poorly managed and maintained.; The fee has been increased unexpectedly.; The receptionist was very rude to her.',
                'correct_answer' => 'The gym didn\'t provide enough information initially.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'listening_id' => 2,
                'title' => 'How does Ms. Londale feel about being charged the processing fee?',
                'answer' => 'She understands that it is part of the contract.; She is happy that the fee wasn\'t as high as she expected.; She is angry that she was told differently when she joined.; She felt that it was not an important matter.',
                'correct_answer' => 'She understands that it is part of the contract.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'listening_id' => 3,
                'title' => 'Next you will listen to four statements. Choose the one that best describes what you see in the picture.',
                'answer' => 'The man is on a pathway.;The mountains are covered with snow.;The man is carrying a cap.;The sandals are in the water.',
                'correct_answer' => 'The man is on a pathway.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'listening_id' => 3,
                'title' => 'What is the main purpose of the notice?',
                'answer' => 'To inform readers of a useful website; To describe the Japan-America Society of Greater Long Island; To instruct people how to write poetry; To announce an upcoming workshop',
                'correct_answer' => 'To inform readers of a useful website',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'listening_id' => 3,
                'title' => 'What information is NOT given in the notice?',
                'answer' => 'The workshop instructor\'s name; Late registration instructions; Cancellation instructions; Things to bring to the workshop',
                'correct_answer' => 'The workshop instructor\'s name',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'listening_id' => 4,
                'title' => 'How many people are coming to the conference?',
                'answer' => 'There were 70 people there.;I don\'t think she is coming.;At least 150 people.',
                'correct_answer' => 'At least 150 people.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'listening_id' => 4,
                'title' => 'According to the notice, who is the workshop tailored to?',
                'answer' => 'Intermediate sushi chefs; Beginner sushi chefs; New JGA members; All JGA members',
                'correct_answer' => 'Intermediate sushi chefs',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'listening_id' => 4,
                'title' => 'Why is the LBA holding a meeting?',
                'answer' => 'To review its bylaws; To revise its voting procedures; To inspire new members to join; To choose a new president',
                'correct_answer' => 'To review its bylaws',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'listening_id' => 5,
                'title' => 'Do you think the boss will take us out for lunch today?',
                'answer' => 'I had a hamburger and fries.;He\'s probably too busy today.;I didn\'t take the bus.',
                'correct_answer' => 'He\'s probably too busy today.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'listening_id' => 5,
                'title' => 'If Ms. LeChevre cannot attend the meeting, what should she do?',
                'answer' => 'Complete a mail-in ballot; Send an apology letter to the president; Make a financial contribution to the LBA; Run for president',
                'correct_answer' => 'Complete a mail-in ballot',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'listening_id' => 5,
                'title' => 'What is attached to the letter?',
                'answer' => 'LBA\'s budget status; A annual calendar of events; Profiles of those running for president; A directory of small businesses',
                'correct_answer' => 'LBA\'s budget status',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'listening_id' => 5,
                'title' => 'What can be inferred about Ms. LeChevre?',
                'answer' => 'She wants to be president.; She works for the president.; She takes charge of counting the ballots.; She is a member of the LBA.',
                'correct_answer' => 'She wants to be president.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'listening_id' => 6,
                'title' => 'Did you fax the letter to the client?',
                'answer' => 'I\'ll type it after lunch.;No; I sent it by email.;I collected some important facts.',
                'correct_answer' => 'No, I sent it by email.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'listening_id' => 6,
                'title' => 'What is the article mainly about?',
                'answer' => 'The state of a city\'s local economy; The rise of the employment rate; The relocation of a company; The improvement of an existing tax law',
                'correct_answer' => 'The state of a city\'s local economy',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'listening_id' => 6,
                'title' => 'What is indicated about lntersil Corp?',
                'answer' => 'The existing headquarters is in Milpitas.; Its business is expanding.; It has a cost-effective environment.; It has highly skilled workers.',
                'correct_answer' => 'The existing headquarters is in Milpitas.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'listening_id' => 6,
                'title' => 'The word "surpass" in paragraph 3, line 3, is closest in meaning to',
                'answer' => 'exceed; include; develop; accelerate ',
                'correct_answer' => 'exceed',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'listening_id' => 7,
                'title' => 'Did you have to wait very long?',
                'answer' => 'No more than an hour.;I hate long line-ups.;I\'ve gained twenty pounds.',
                'correct_answer' => 'No more than an hour.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'listening_id' => 7,
                'title' => 'How does the CEO feel about the company\'s plan?',
                'answer' => 'anxious ; angry ; depressed ; confident',
                'correct_answer' => 'anxious ',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'listening_id' => 7,
                'title' => 'What is the purpose of the notice?',
                'answer' => 'Inform residents of an increase in utility fees;Advertise a room for rent;Update new regulations for tenants;Recruit a manager for an apartment building',
                'correct_answer' => 'Inform residents of an increase in utility fees',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'listening_id' => 7,
                'title' => 'What is included in the notice?',
                'answer' => 'All utilities are included in the rent;The kitchen is not spacious;,It is close to public transportation;Onsite parking is available',
                'correct_answer' => 'All utilities are included in the rent',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 26,
                'listening_id' => 8,
                'title' => 'What are the man and woman mainly discussing?',
                'answer' => 'A vacation;A budget;A company policy;A conference',
                'correct_answer' => 'A conference',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'listening_id' => 8,
                'title' => 'How is the woman traveling?',
                'answer' => 'By plane;By bus;By taxi;By car',
                'correct_answer' => 'By bus',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'listening_id' => 8,
                'title' => 'Why aren\'t the man and woman going together?',
                'answer' => 'The woman needs to arrive earlier.;The man has to work overtime.;The woman dislikes air travel.;The man has to go to the bank first.',
                'correct_answer' => 'The woman dislikes air travel.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'listening_id' => 9,
                'title' => 'What does the man have to do today?',
                'answer' => 'Visit his lawyer;Get a massage;Go to the doctor;Make an appointment',
                'correct_answer' => 'Go to the doctor',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'listening_id' => 9,
                'title' => 'What can be inferred from the conversation?',
                'answer' => 'The woman is the man\'s receptionist.;The lawyer works in the same building.;The woman has no deadlines today.;The man and woman have a meeting this afternoon.',
                'correct_answer' => 'The woman has no deadlines today.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'listening_id' => 9,
                'title' => 'What does the woman offer to do for the man?',
                'answer' => 'Answer his phone;Call his lawyer;Pick up the newspaper;Take notes at the meeting',
                'correct_answer' => 'Answer his phone',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'listening_id' => 10,
                'title' => 'What should the passengers do before exiting the ship?',
                'answer' => 'Welcome the visitors;Check the time;Collect their personal item;Take a picture',
                'correct_answer' => 'Collect their personal items',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 33,
                'listening_id' => 10,
                'title' => 'What does the speaker imply?',
                'answer' => 'The water was rough.;The weather was poor yesterday.;The tour went faster than usual.;There is only one way to exit.',
                'correct_answer' => 'The weather was poor yesterday.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'listening_id' => 10,
                'title' => 'What will happen in five minutes?',
                'answer' => 'The ship will arrive at the dock.;The passengers will go shopping.;The passengers will take photos of the ship.;The market will open.',
                'correct_answer' => 'The ship will arrive at the dock.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'listening_id' => 11,
                'title' => 'How often does this event take place?',
                'answer' => 'Monthly;Four times a year;Once a year;Every four years',
                'correct_answer' => 'Once a year',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'listening_id' => 11,
                'title' => 'What will happen after the brunch?',
                'answer' => 'The people will be served drinks.;An artist will show his drawings.;The guests will introduce themselves.;A poet will read a poem.',
                'correct_answer' => 'A poet will read a poem.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 37,
                'listening_id' => 11,
                'title' => 'What do guests get to take home?',
                'answer' => 'Lunch;A book of mythology;A collection of poems;A painting',
                'correct_answer' => 'A collection of poems',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 38,
                'listening_id' => 12,
                'title' => 'Where would you hear this type of talk?',
                'answer' => 'In an airport;At a bus station;On a telephone;On television',
                'correct_answer' => 'On a telephone',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'listening_id' => 12,
                'title' => 'Who should visit the website?',
                'answer' => 'Staff members of Speedy Reservations;Callers looking for special schedules;Callers looking for staff members;People looking for fight times',
                'correct_answer' => 'Callers looking for special schedules',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 40,
                'listening_id' => 12,
                'title' => 'What is the quickest way to get connected to a representative?',
                'answer' => 'Hang up and call again;Call back later;Wait patiently;Call a different number',
                'correct_answer' => 'Wait patiently',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],

        ]);
//        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
}
