<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ListeningQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('listening_questions')->truncate();
        DB::table('listening_questions')->insert([
            [
                'id' => 1,
                'listening_id' => 1,
                'title' => 'Next you will listen to four statements. Choose the one that best describes what you see in the picture.',
                'answer' => 'The woman is wearing glasses.,There is a note on the keyboard.,The woman is facing the monitor.,There is a lamp above the computer.',
                'correct_answer' => 'The woman is facing the monitor.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'listening_id' => 2,
                'title' => 'Next you will listen to four statements. Choose the one that best describes what you see in the picture.',
                'answer' => 'The people are wearing coats.,The boat is in the water.,The life-jackets are on the boat.,The drum is in front of the chair.',
                'correct_answer' => 'The drum is in front of the chair.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'listening_id' => 3,
                'title' => 'Next you will listen to four statements. Choose the one that best describes what you see in the picture.',
                'answer' => 'The man is on a pathway.,The mountains are covered with snow.,The man is carrying a cap.,The sandals are in the water.',
                'correct_answer' => 'The man is on a pathway.',
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'listening_id' => 4,
                'title' => 'How many people are coming to the conference?',
                'answer' => 'There were 70 people there.,I don\'t think she is coming.,At least 150 people.',
'correct_answer' => 'At least 150 people.',
'status' => 1,
'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
'id' => 5,
'listening_id' => 5,
'title' => 'Do you think the boss will take us out for lunch today?',
'answer' => 'I had a hamburger and fries.,He\'s probably too busy today.,I didn\'t take the bus.',
'correct_answer' => 'He\'s probably too busy today.',
'status' => 1,
'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 6,
    'listening_id' => 6,
    'title' => 'Did you fax the letter to the client?',
    'answer' => 'I\'ll type it after lunch.,No, I sent it by email.,I collected some important facts.',
'correct_answer' => 'No, I sent it by email.',
'status' => 1,
'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
'id' => 7,
'listening_id' => 7,
'title' => 'Did you have to wait very long?',
'answer' => 'No more than an hour.,I hate long line-ups.,I\'ve gained twenty pounds.',
'correct_answer' => 'No more than an hour.',
'status' => 1,
'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 8,
    'listening_id' => 8,
    'title' => 'What are the man and woman mainly discussing?',
    'answer' => 'A vacation,A budget,A company policy,A conference',
    'correct_answer' => 'A conference',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 9,
    'listening_id' => 8,
    'title' => 'How is the woman traveling?',
    'answer' => 'By plane,By bus,By taxi,By car',
    'correct_answer' => 'By bus',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 10,
    'listening_id' => 8,
    'title' => 'Why aren\'t the man and woman going together?',
'answer' => 'The woman needs to arrive earlier.,The man has to work overtime.,The woman dislikes air travel.,The man has to go to the bank first.',
'correct_answer' => 'The woman dislikes air travel.',
'status' => 1,
'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
'id' => 11,
'listening_id' => 9,
'title' => 'What does the man have to do today?',
'answer' => 'Visit his lawyer,Get a massage,Go to the doctor,Make an appointment',
'correct_answer' => 'Go to the doctor',
'status' => 1,
'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
'id' => 12,
'listening_id' => 9,
'title' => 'What can be inferred from the conversation?',
'answer' => 'The woman is the man\'s receptionist.,The lawyer works in the same building.,The woman has no deadlines today.,The man and woman have a meeting this afternoon.',
'correct_answer' => 'The woman has no deadlines today.',
'status' => 1,
'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 13,
    'listening_id' => 9,
    'title' => 'What does the woman offer to do for the man?',
    'answer' => 'Answer his phone,Call his lawyer,Pick up the newspaper,Take notes at the meeting',
    'correct_answer' => 'Answer his phone',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 14,
    'listening_id' => 10,
    'title' => 'What should the passengers do before exiting the ship?',
    'answer' => 'Welcome the visitors,Check the time,Collect their personal items,Take a picture',
    'correct_answer' => 'Collect their personal items',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 15,
    'listening_id' => 10,
    'title' => 'What does the speaker imply?',
    'answer' => 'The water was rough.,The weather was poor yesterday.,The tour went faster than usual.,There is only one way to exit.',
    'correct_answer' => 'The weather was poor yesterday.',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 16,
    'listening_id' => 10,
    'title' => 'What will happen in five minutes?',
    'answer' => 'The ship will arrive at the dock.,The passengers will go shopping.,The passengers will take photos of the ship.,The market will open.',
    'correct_answer' => 'The ship will arrive at the dock.',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 17,
    'listening_id' => 11,
    'title' => 'How often does this event take place?',
    'answer' => 'Monthly,Four times a year,Once a year,Every four years',
    'correct_answer' => 'Once a year',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 18,
    'listening_id' => 11,
    'title' => 'What will happen after the brunch?',
    'answer' => 'The people will be served drinks.,An artist will show his drawings.,The guests will introduce themselves.,A poet will read a poem.',
    'correct_answer' => 'A poet will read a poem.',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 19,
    'listening_id' => 11,
    'title' => 'What do guests get to take home?',
    'answer' => 'Lunch,A book of mythology,A collection of poems,A painting',
    'correct_answer' => 'A collection of poems',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 20,
    'listening_id' => 12,
    'title' => 'Where would you hear this type of talk?',
    'answer' => 'In an airport,At a bus station,On a telephone,On television',
    'correct_answer' => 'On a telephone',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 21,
    'listening_id' => 12,
    'title' => 'Who should visit the website?',
    'answer' => 'Staff members of Speedy Reservations,Callers looking for special schedules,Callers looking for staff members,People looking for fight times',
    'correct_answer' => 'Callers looking for special schedules',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],
[
    'id' => 22,
    'listening_id' => 12,
    'title' => 'What is the quickest way to get connected to a representative?',
    'answer' => 'Hang up and call again,Call back later,Wait patiently,Call a different number',
    'correct_answer' => 'Wait patiently',
    'status' => 1,
    'created_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
    'updated_at' => \Illuminate\Support\Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
],

        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
}
